Revert "Remove unused type variables."
This reverts commit 156e38b7ae0e4ea7941dc1d2dbc9b4aeb515f1f6.

This change was not compatible with GHC 8.6.5:

    src/Cardano/Ledger/Era.hs:92:25: error:
        Unexpected type ‘_’
        In the default declaration for ‘TranslationError’
        A default declaration should have form
          default TranslationError a b = ...
       |
    92 |   type TranslationError _ _ = Void

I don't think we (read: all downstream repos) are ready yet to burn that bridge,
at least not for something so trivial as this.